Vagrant.configure("2") do |config|

  config.vm.hostname = "simple-zookeeper"

  config.vm.box =  ENV['VAGRANT_BOX'] || "lucid64"
  config.vm.box_url = ENV['VAGRANT_BOX_URL'] || "http://files.vagrantup.com/lucid64.box"

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  config.vm.network :forwarded_port, guest: 8080, host: 8082, auto_correct: true
  config.vm.network :forwarded_port, guest: 2181, host: 2181, auto_correct: true

  config.ssh.max_tries = 40
  config.ssh.timeout   = 120

  config.vm.provision :chef_solo do |chef|
    chef.json = {
        :exhibitor => {
          :opts => {
            :configtype => "file",
            :s3backup => "false"
          },
          :snapshot_dir => "/tmp/zookeeper",
          :transaction_dir => "/tmp/zookeeper",
          :log_index_dir => "/tmp/zookeeper_log_indexes",
          :hostname => "http://localhost:8080"
        }
    }

    chef.run_list = [
      "recipe[apt]",
      "recipe[java_simple::default]",
      "recipe[simple-zookeeper::default]"
    ]
  end
end
